---
- name: Create NFS Server automount unit file
  template:
    src: templates/nfsshare.automount.j2
    dest: "/etc/systemd/system/{{ client_share_folder_systemd }}.automount"
    owner: root
    group: root
    mode: "u=rwx,g=,o="
  notify: "enable automount"

# - name: Enable automount unit file
#   ansible.builtin.systemd_service:
#     state: started
#     enabled: true
#     name: nfs-example.automount
